name: .NET

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:
    inputs:
      dd_trace_repo:
        description: "DD-Trace repository (org/repo)"
        required: false
        default: "DataDog/dd-trace-dotnet"
      dd_trace_branch:
        description: "Branch in dd-trace-dotnet fork to test"
        required: true
        default: "master"

env:
  DD_TRACE_BRANCH: ${{ github.event.inputs.dd_trace_branch || 'master' }}
  DD_TRACE_REPO: ${{ github.event.inputs.dd_trace_repo || 'DataDog/dd-trace-dotnet' }}
  DD_ENV: ci
  DD_SERVICE: testing-playground
  DD_VERSION: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Clone and build DD-Trace
        run: |
          echo "Cloning DD-Trace from $DD_TRACE_REPO branch $DD_TRACE_BRANCH"
          set -x
          git clone https://github.com/$DD_TRACE_REPO.git dd-trace-dotnet
          cd dd-trace-dotnet
          git checkout $DD_TRACE_BRANCH

          # Navigate to the tracer directory where the build scripts are located
          cd tracer
          ls
          # Build the tracer using Nuke
          chmod +x build.sh
          ./build.sh Clean BuildTracerHome

          # The tracer home should be in tracer/bin/tracer-home
          echo "DD_DOTNET_TRACER_HOME=$PWD/bin/tracer-home" >> $GITHUB_ENV

          # Set environment variables for the tracer
          echo "CORECLR_ENABLE_PROFILING=1" >> $GITHUB_ENV
          echo "CORECLR_PROFILER={846F5F1C-F9AE-4B07-969E-05C26BC060D8}" >> $GITHUB_ENV
          echo "CORECLR_PROFILER_PATH=$PWD/bin/tracer-home/Datadog.Trace.ClrProfiler.Native.so" >> $GITHUB_ENV
          echo "DD_TRACE_ENABLED=true" >> $GITHUB_ENV
          echo "DD_LOGS_INJECTION=true" >> $GITHUB_ENV
          echo "DD_PROFILING_ENABLED=false" >> $GITHUB_ENV

          # Enable CI visibility
          echo "DD_CIVISIBILITY_ENABLED=true" >> $GITHUB_ENV
          echo "DD_CIVISIBILITY_AGENTLESS_ENABLED=true" >> $GITHUB_ENV

          # Set API key if available
          if [ -n "${{ secrets.DD_API_KEY }}" ]; then
            echo "DD_API_KEY=${{ secrets.DD_API_KEY }}" >> $GITHUB_ENV
            echo "DD_SITE=${{ secrets.DD_SITE || 'datadoghq.com' }}" >> $GITHUB_ENV
            echo "API key configured, traces will be sent to Datadog"
          else
            echo "No API key found, running in local mode only"
          fi

          # Log to console for debugging
          echo "DD_TRACE_DEBUG=true" >> $GITHUB_ENV

          # Show final configuration
          echo "=== DD-Trace Configuration ==="
          echo "DD_DOTNET_TRACER_HOME: $PWD/bin/tracer-home"
          ls -la "$PWD/bin/tracer-home" || echo "Tracer home not found"
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
